default_agent: aria_banking_agent
agents:
  aria_banking_agent:
    name: aria_banking_agent
    language: python
    node_version: null
    entrypoint: aria/agentcore_app.py
    deployment_type: container
    runtime_type: null
    platform: linux/amd64
    container_runtime: null
    source_path: null
    aws:
      execution_role: arn:aws:iam::395402194296:role/AmazonBedrockAgentCoreSDKRuntime-eu-west-2-3aa478434d
      execution_role_auto_create: false
      account: '395402194296'
      region: eu-west-2
      ecr_repository: 395402194296.dkr.ecr.eu-west-2.amazonaws.com/bedrock-agentcore-aria_banking_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: 1800
        max_lifetime: 28800
    bedrock_agentcore:
      agent_id: aria_banking_agent-ubLoKG8xsY
      agent_arn: arn:aws:bedrock-agentcore:eu-west-2:395402194296:runtime/aria_banking_agent-ubLoKG8xsY
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-aria_banking_agent-builder
      execution_role: arn:aws:iam::395402194296:role/AmazonBedrockAgentCoreSDKCodeBuild-eu-west-2-3aa478434d
      source_bucket: bedrock-agentcore-codebuild-sources-395402194296-eu-west-2
    memory:
      mode: STM_AND_LTM
      memory_id: aria_bank_mem-8K8rec3DDr
      memory_arn: null
      memory_name: aria_banking_agent
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
