#!/usr/bin/env bash
# setup-github.sh
# ----------------
# Sets GitHub Actions secrets and variables for this repository.
# Requires the GitHub CLI (gh) to be authenticated: gh auth login
#
# Usage:
#   chmod +x setup-github.sh
#   ./setup-github.sh
#
# ⚠️  Review credential values before running.
#     This script was generated by amazon-connect-chat-tester setup.

set -euo pipefail

echo "Setting GitHub Actions secrets and variables..."

# ── AWS (secret) ─────────────────────────────────────────────────────────────
gh secret set AWS_ROLE_ARN --body "arn:aws:iam::395402194296:oidc-provider/token.actions.githubusercontent.com"

# Zephyr Squad disabled
gh variable set ZEPHYR_ENABLED  --body "false"

# ── Amazon Connect (variables — non-sensitive) ────────────────────────────────
gh variable set AWS_REGION              --body "eu-west-2"
gh variable set CONNECT_INSTANCE_ID     --body "f969d4b4-f716-4974-a325-bb7899f2f293"
gh variable set CONNECT_CONTACT_FLOW_ID --body "arn:aws:connect:eu-west-2:395402194296:instance/f969d4b4-f716-4974-a325-bb7899f2f293/contact-flow/f6d6545f-c9ae-4ca4-a4d8-6fdc8ba0494f"
gh variable set CHAT_TIMEOUT_SECONDS    --body "10"
gh variable set CHAT_DURATION_MINUTES   --body "5"

echo ""
echo "Done! GitHub Actions secrets and variables are set."
echo "Trigger the workflow at:"
echo "  .github/workflows/connect_chat_zephyr_suite.yml"
